version: "3"

services:
  application:
    image: ${DOCKER_IMAGE}
    container_name: ilgijjan-server
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - rabbitmq
    volumes:
      - ./logs:/logs
    networks:
      - ilgijjan-net

  redis:
    image: redis:latest
    container_name: ilgijjan-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ilgijjan-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ilgijjan-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ilgijjan-net
      -
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: always
    networks:
      - ilgijjan-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    depends_on:
      - prometheus
    networks:
      - ilgijjan-net

  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
      - ./gcp-key.json:/etc/loki/gcp-key.json
    command: -config.file=/etc/loki/local-config.yml
    ports:
      - "3100:3100"
    restart: always
    networks:
      - ilgijjan-net

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./logs:/var/log/ilgijjan
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml
    restart: always
    networks:
      - ilgijjan-net

networks:
  ilgijjan-net:
    external: true